### ISSUE TITLE
Issue when using with CRA 5.0.0

### ISSUE THREAD

**Issue by bpod** [briansokol/eslint-config#52]
When upgrading to CRA 5.0.0 in an existing app, started getting these errors at compile time.

`ERROR in Failed to load plugin '@typescript-eslint' declared in '.eslintrc » @bsokol/eslint-config/react-typescript': Class extends value undefined is not a constructor or null
Referenced from: [...]/node_modules/@bsokol/eslint-config/react-typescript.js`

Installation succeeds. I don't start seeing this until compile time. Let me know if you need any more context/details. 

My Current versions...

"@bsokol/eslint-config": "^6.0.2",
"typescript": "^4.2.4",
"react-scripts": "5.0.0",

**Comment by briansokol** [comment]
@bpod I updated everything to the latest versions and adjusted all the configs to match. Rules should not have changed. Looks like any newly added rules are still off. This will require ESLint 8 and newer versions of Node. Check the release notes for details.

https://github.com/briansokol/eslint-config/releases/tag/v7.0.0

Let me know if you're still having issues after pulling in the latest version.

**Comment by befreestudios** [comment]
Yep, this fixed the issues I was running into. Thank you!
